"""empty message

Revision ID: 3420604479b7
Revises: faa9d1992c39
Create Date: 2024-12-28 10:18:20.944769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '3420604479b7'
down_revision: Union[str, None] = 'faa9d1992c39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('series', schema=None) as batch_op:
        batch_op.alter_column('portada',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('series', schema=None) as batch_op:
        batch_op.alter_column('portada',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
