"""empty message

Revision ID: 5b10c40f9ace
Revises: 3420604479b7
Create Date: 2024-12-30 17:11:38.319423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '5b10c40f9ace'
down_revision: Union[str, None] = '3420604479b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('peliculas', schema=None) as batch_op:
        batch_op.alter_column('portada',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('video',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('sinopsis',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('peliculas', schema=None) as batch_op:
        batch_op.alter_column('sinopsis',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('video',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('portada',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
