"""empty message

Revision ID: babca463517f
Revises: 5b10c40f9ace
Create Date: 2025-01-26 12:06:56.059448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'babca463517f'
down_revision: Union[str, None] = '5b10c40f9ace'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('capitulos', schema=None) as batch_op:
        batch_op.alter_column('sinopsis_capitulo',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('video',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.create_foreign_key(None, 'series', ['serie_id'], ['id'])

    with op.batch_alter_table('peliculas', schema=None) as batch_op:
        batch_op.alter_column('video',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('series', schema=None) as batch_op:
        batch_op.alter_column('portada',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('sinopsis',
               existing_type=sa.VARCHAR(),
               nullable=False)

    with op.batch_alter_table('usuario_capitulos', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'usuarios', ['usuario_id'], ['id'])
        batch_op.create_foreign_key(None, 'capitulos', ['capitulo_id'], ['id'])

    with op.batch_alter_table('usuario_peliculas', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'usuarios', ['usuario_id'], ['id'])
        batch_op.create_foreign_key(None, 'peliculas', ['pelicula_id'], ['id'])

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['username'])
        batch_op.create_unique_constraint(None, ['email'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('usuario_peliculas', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('usuario_capitulos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('series', schema=None) as batch_op:
        batch_op.alter_column('sinopsis',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('portada',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('peliculas', schema=None) as batch_op:
        batch_op.alter_column('video',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('capitulos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('video',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('sinopsis_capitulo',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
