"""empty message

Revision ID: faa9d1992c39
Revises: 
Create Date: 2024-12-19 08:16:27.053063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'faa9d1992c39'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('capitulos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('serie_id', sa.Integer(), nullable=False),
    sa.Column('titulo_capitulo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('num_capitulo', sa.Integer(), nullable=False),
    sa.Column('num_temporada', sa.Integer(), nullable=False),
    sa.Column('sinopsis_capitulo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('video', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('duracion', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('peliculas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('duracion', sa.Integer(), nullable=False),
    sa.Column('portada', sa.Integer(), nullable=False),
    sa.Column('video', sa.Integer(), nullable=False),
    sa.Column('sinopsis', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('series',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('portada', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sinopsis', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('num_temporadas', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario_capitulos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('capitulo_id', sa.Integer(), nullable=False),
    sa.Column('visto', sa.Boolean(), nullable=False),
    sa.Column('favorito', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario_peliculas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('pelicula_id', sa.Integer(), nullable=False),
    sa.Column('visto', sa.Boolean(), nullable=False),
    sa.Column('favorito', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('admin', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuarios')
    op.drop_table('usuario_peliculas')
    op.drop_table('usuario_capitulos')
    op.drop_table('series')
    op.drop_table('peliculas')
    op.drop_table('capitulos')
    # ### end Alembic commands ###
